### ISSUE TITLE
wifi.txt のフォーマット確認・実行時エラー確認 (失敗すると WiFi に繋がらなくなる)

### ISSUE THREAD

**Issue by dynamis** [webdino/pizero-workshop#12]
9/3 ビルドテストでの問題報告。初回起動時に USB からのネットワーク共有で接続した状態で wifi.txt 編集して設定したケースだが、
/etc/wpa_supplicant/wpa_supplicant.conf の中に明らかに wpa_passphrase のコマンド実行失敗の結果が含まれたりしている

```
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

usage: wpa_passphrase <ssid> [passphrase]

If passphrase is left out, it will be read from stdin
network={
  ...
}
```

なお、Buster からは WiFi の country 設定をしないと WiFi に繋がらない。

```
sudo raspi-config nonint do_wifi_country JP
```

このコマンドで wpa_supplicant.confに country が追加される:

```
country=JP
```

この設定が入った上で再起動する (wpa_supplicant サービスだけ再起動すれば良い？) と接続可能になるハズ。

**Comment by dynamis** [comment]
上記、改行だけの wifi.txt を渡した場合に再現。

また、パススレーズが短すぎる指定の wifi.txt を指定した場合は次のエラーメッセージが wpa_supplicant.conf に書き込まれてしまう。

```
If passphrase is left out, it will be read from stdin
Passphrase must be 8..63 characters
usage: wpa_passphrase <ssid> [passphrase]
```

いずれも、一度なると /boot 配下の編集だけでは復旧不能になるので致命傷です。

- [ ] パスフレーズ部分の文字数が不適切な場合に WiFi 接続不能になる
  - こちらは致命的なので必ず速やかに修正が必要
- [ ] ssid に "," を含むアクセスポイントに接続できない (ssid に利用可能な文字が実際の仕様より狭いフォーマットになってしまっている)
  - 来週はそのようなアクセスポイントには繋がないので後回しでも良いです

**Comment by dynamis** [comment]
仕様書通りの実装を完全にしているわけではない以上、フォーマット確認が不完全なことがあるので wpa_passphrase の実行結果確認も

- wpa_passphrase 実行結果がエラーの場合は wpa_supplicant.conf を上書きしない
  - [ ] wpa_passphrase コマンド実行結果の確認
  - [ ] 失敗している場合には wpa_supplicant.conf を元のまま保持 (全て上手くいって始めてファイル書き換えを行う)
- [ ] wifi.txt に問題があった場合は何が悪いか分かるようにログを残す

**Comment by takashinishio** [comment]
改行だけのwifi.txtのisuue
wifi.txtnおパスフレーズの文字数のissue
wpa_passphraseの終了コードチェックでのwpa_supplicant.confの書き換えからの保護issue

以上３つのissueに対応しました。
ログと、利用可能な文字は、近々対応する予定です。

**Comment by kou029w** [comment]
jsに移行したためクローズ
https://webdino.github.io/pizero-workshop/ForDevelopers/pizero-workshopForDevelopers.html
https://webdino.github.io/pizero-workshop/ForDevelopers/bootWifi.html
