### ISSUE TITLE
log ディレクトリにログファイルを含めない

### ISSUE THREAD

**Issue by dynamis** [webdino/pizero-workshop#13]
- [x] 既にコミットされているものは削除
- [x] log/.gitignore で log 配下のファイルを含めないように指定
- ~~log/.gitkeep ファイルを追加してディレクトリ自体は保持する~~

**Comment by dynamis** [comment]
log/.gitignore を以下の内容で作成が良かったかも:

```
*
!.gitignore
```

**Comment by takashinishio** [comment]
logディレクトリに空の.gitkeepファイルをつくって、
pizero-workshopの.gitignoreに
log/*
!.gitkeep
と記述することで一応対応しました。
