### ISSUE TITLE
rclone の設定をある程度自由に出来ると嬉しい

### ISSUE THREAD

**Issue by dynamis** [webdino/pizero-workshop#14]
rclone はできるが pizero-workshop サブディレクトリに毎日 0 時に同期する固定設定となっているのをもう少し柔軟に出来ると嬉しい。また実行タイミングは複数タスク同時は避ける。

- [x] rsync と同時に rclone を実行せず、rsync 終わってから rclone すべき
  - rclone で gdrive に同期中のディレクトリの中身が rsync で書き換えられるという状態になってしまっているので rsync してから rclone するのを一つのタスクとして登録するか、単に実行時間を十分な時間 (数分) ずらす必要がある。
- [x] 定時実行のタイミングを /boot/settings 配下から変更可能に
  - 毎日何時に実行するかの時間のリスト (crontab 2 つ目の時間指定部分) だけでも指定できると良いかも 
- [x] サブディレクトリ名を /boot/setting 配下のファイルから変更可能に
  - 今のところ rclone.txt の `root_folder_id` を変えることで同じアカウントに複数端末からの Upload も可能だが、サブディレクトリ名も変更可能だとより嬉しい

サブディレクトリハードコーディング箇所:
https://github.com/webdino/pizero-workshop/blob/bcdf522050ca2d3031917ecca6a21bf414d96b83/rclone.sh#L13

crontab 設定:
https://github.com/webdino/pizero-workshop/blob/bcdf522050ca2d3031917ecca6a21bf414d96b83/setup2.sh#L70
```
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
@reboot	       root $dir/setup.sh -wifi_txt
@reboot	       root /sbin/iw dev wlan0 set power_save off
@reboot	       root $dir/pizero-workshop-starter.sh
#*/1 * * * *    pi bash -c "$dir/traffic.sh >> $dir/log/traffic.csv"
00 0 * * *  root $dir/rclone.sh
00 0 * * *  root rsync -a $dir/log/ /boot/setting/log/
@reboot     root rsync -a $dir/log/ /boot/setting/log/
```

**Comment by dynamis** [comment]
優先度と設定の書き方については次の通りです:

- rsync 後に rclone するという順序にするのは正常動作させるため必須かと思います (現状はデータ量が増えると再現するバグという状態)
  - 現状 rclone と rsync 逆じゃないですか？ (echo と実行コマンドが対応してない)
  - https://github.com/webdino/pizero-workshop/blob/master/script/start.sh#L108
- rsync / rclone は個別に設定できれば rsync 頻度は高いが rclone は少ないといったこともできるが、今のところ重要なものではないので常にペア実行で構いません。
- rsync+rclone の実行頻度とタイミングは再起動時のオンオフ + 整数 N 時間毎で設定したいです
  - 24 以上、例えば 168 を指定すれば週に一度とかにもできる
  - もし crontab の書き換えで実行するなら N は 24 の因数または倍数しか指定できないといった制約を設けてくれても構いません
- 設定ファイルは wifi も統合されてるので config.js にまとめられるのが良さそうです
  - rclone.conf は機械生成出来るファイルなので外部から書き換えたくない
  - rclone.conf 内で設定可能なものはそちらを用い、それ以外を config.js で扱う
  - 例えばこんな感じ:

```js
// ...
  syncLogs: {
    rsyncIntervalHours: 2,
    rcloneIntervalHours: 48,
    rcloneDestDir: "pizero-workshop"
  },
// ...
```

ちなみに、ディレクトリ名の変数名に from / to は (これら前置詞が広く使われすぎるもので意味が絞られないので) あまり良くないです。また、他のツール・ライブラリ・クラスなどと連携するときに用語が変わるのも良くないです。都度対応をコードやドキュメントを見て調べるのではなく、変数名から自ずと明らかになっていることが大事です。

この場合、具体的には  rclone の引数に渡す物ですから `rclone copy --help` で出てくる usage などと用語を合わせて source / dest とすべきです:

```
$ rclone copy --help
Copy the source to the destination.  Doesn't transfer
unchanged files, testing by size and modification time or
MD5SUM.  Doesn't delete files from the destination.

Note that it is always the contents of the directory that is synced,
not the directory so when source:path is a directory, it's the
contents of source:path that are copied, not the directory name and
contents.

If dest:path doesn't exist, it is created and the source:path contents
go there.

For example

    rclone copy source:sourcepath dest:destpath
...
Usage:
  rclone copy source:path dest:path [flags]
...
```

**Comment by kou029w** [comment]
syncLog実装されて設定できるようになったのでクローズ
https://webdino.github.io/pizero-workshop/ForDevelopers/syncLog.html

execSync で rsync 終わってから rclone される
https://github.com/webdino/pizero-workshop/blob/b3d494fdfc202fc944ea117033aac41997654b6a/syncLog/syncLog.js#L23
