### ISSUE TITLE
エラーログ出力の整理

### ISSUE THREAD

**Issue by dynamis** [webdino/pizero-workshop#15]
sdcard だけで編集するので、設定ファイル類にの記述に問題があるときはその問題がエラーログで分かるようにしたい。

- wifi.txt
  - フォーマットのエラーがあればその旨を出力
  - どの行に問題があるのか分かるのが望ましい
- config.js
  - js としての構文エラーがあればそのエラーを出力。eslint ログだとなお良い。
  - 構文の問題は無いが必須の設定値がない場合はその旨を出力したい
  - 設定としてあってはならない値が入っている場合もその旨を出力したい
  - address のフォーマットは検査して間違いがあれば出力したい (典型的な間違いは : 付きで書く人。アドレス書かれたシール見ながら書かせるときは問題ないけどコマンドとかツールで Mac アドレス調べるときにはよくある)
- rclone.txt
  - 設定ファイルの間違いがあれば。。。まぁ rclone コマンドで生成するのが普通なので rclone の実行エラーだけ記録できれば十分
- hostname
  - フォーマットエラーがあれば

また、現在 error.txt に "false" とだけ出力されるケースが見られるのが謎。

**Comment by dynamis** [comment]
設定ファイルの確認とログはこちらで再実装:
https://github.com/webdino/pizero-workshop/blob/master/script/checkConfig.js

**Comment by kou029w** [comment]
チェック機構があるのでクローズ
https://webdino.github.io/pizero-workshop/ForDevelopers/pizero-workshopForDevelopers.html
