### ISSUE TITLE
ローカルで画面・ライトや音声での通知機能

### ISSUE THREAD

**Issue by dynamis** [webdino/pizero-workshop#21]
センサーの値が一定条件を満たした場合にサーバに UP/通知するだけでなく、ローカルで視覚・聴覚による通知を行いたい。工場などに設置するときはまた故障しないようハードなどを選定し直すとして、取りあえず簡単に試せるものとして作る。

## 視覚通知

単純に小型の Raspberry Pi 向けディスプレイを繋いでブラウザをフル画面表示すれば現在のセンサーの値を表示しつつ、背景色の変化で通知が可能。パネルの明るさの変更は多分出来ないので諦める。細かな表示は要らないからとにかく明るく色などで通知をして欲しいケースであれば WS2812B のカラー LED HAT をつけて通知するのがよさそう。

- RasPi サイズの 3.5inch 480x320 HDMI ディスプレイ (MPI3508 など) が結構一杯あり
  - MPI3508 https://www.amazon.co.jp/dp/B07VSB4TS2/
    - ケース付き1台目のみクーポン値引き https://www.amazon.co.jp/dp/B07TXTSJBY/
  - SPI 接続ディスプレイがより安価だがドライバの導入などが必要。手軽・汎用かつ 60fps 駆動できるのは HDMI。音声出力もある
  - AliExpress $17 前後だが送料注意 https://ja.aliexpress.com/item/32818537950.html
- 解像度低すぎるなら RasPi 4.0inch 800x480 HDMI ディスプレイ
  - AliExpressにて $22.56 https://ja.aliexpress.com/item/33057280844.html
- 大きくても良ければ RasPi 5.0inch 800x480 HDMI ディスプレイ。但し音声出力無し
  - クーポン値引きで3500円 https://www.amazon.co.jp/dp/B07DHDP8D3/
  - AliExpress なら $20.9 https://ja.aliexpress.com/item/32993813607.html
- Color LED (WS2812B) HAT
  - https://ja.aliexpress.com/item/32901953889.html
  - https://www.physical-computing.jp/phone/product/1347
- Pizero サイズの横長 LCD は見当たらない。PiZero 向けデザインであるのはこれくらい
  - https://ja.aliexpress.com/item/33040557506.html
  - https://www.physical-computing.jp/phone/product/1599
  - e-ink ディスプレイ HAT などはあるが 3 color のみで制御も面倒なので手を出さない

## 聴覚通知

HDMI ディスプレイだと音声出力端子も付いているのでそれを 100 均で帰る 100〜300 円くらいのスピーカーに接続し、音声ファイルを再生させるのがシンプル。

音声合成などはしても良いけど事前にしたファイルを再生しておけば良いんじゃないか。数値読み上げするなら音声合成をすることになるが。。。

**Comment by dynamis** [comment]
100 均のスピーカーなかなか置いてないので Amazon ピックアップ:

- 無難なのは USB 電源
  - ステレオで場所取る
    - ダイソー300円の色違い？ 473円 https://www.amazon.co.jp/dp/B07XQHRCS9/
    - iBuffalo 598円 https://www.amazon.co.jp/dp/B01JI045RQ/
    - その他 https://www.amazon.co.jp/dp/B079ZVK9LP/
  - 小型あるかな？
- コンパクトなのは 電池 (単三x2) 駆動ジャック直刺し
  - 253円 https://www.amazon.co.jp/dp/B07W5M5CQN/
  - 589円 https://www.amazon.co.jp/dp/B07K6M1285/
  - 828円 https://www.amazon.co.jp/dp/B07RLMKB7C/
  - 電池すぐ切れそうだけど RasPi 3.3v から給電できるかも？
- 屋内 Bluetooth
  - 謎デザイン 494円,499円,506円... https://www.amazon.co.jp/dp/B07WTYRKHQ/
  - 561円 https://www.amazon.co.jp//dp/B07WT214RQ/
  - シンプルファブリックデザイン 996円 https://www.amazon.co.jp/dp/B07LG66FQH/
  - コンパクト 1480円 https://item.rakuten.co.jp/auc-carover/gd-mbspk/
- 防水 Bluetooth (USB 給電+バッテリー)
  - 円形 - 音量記憶してくれないかも？
    - 581円 グリーン https://www.amazon.co.jp/dp/B07SCMXFVC/
    - 582円 レッド https://www.amazon.co.jp/dp/B07SBNBWSQ/
    - 899円 https://www.amazon.co.jp/dp/B07YKDSC3V/
  - 丸筒型
    - 666円 黒 https://www.amazon.co.jp/dp/B07TXP5H3W/
- 無電源 (音小さい)
  - https://www.amazon.co.jp/dp/B07V68Y2WY/

**Comment by dynamis** [comment]
配線系のメモを追加:

- HDMI - HDMI mini の配線
  - L 字ケーブル類は隣の USB, オーディオ端子と干渉することが多いので要注意
  - 30cm ケーブル https://ja.aliexpress.com/item/32519099637.html
    - 1 ドル程度送料無料で入手可能。ケーブル柔らかくはない。白もあるのは良い
  - 普通の ELECOM ケーブル https://www.amazon.co.jp/dp/B00HQY7W22/
  - FPV https://ja.aliexpress.com/item/32982250238.html
    - 価格を気にせず綺麗にするのには良いが USB ケーブルなどとの干渉に要注意
- USB OTG
  - キャンドゥとか 100 均で入手可能
  - Pi Zero キット同梱品は OMRON センサー指すと壊れるダメなやつなので使わないこと
  - ELECOM https://www.amazon.co.jp/dp/B0197AP91S/
  - ノーブランド https://www.amazon.co.jp/dp/B07WYYSRN3/ https://www.amazon.co.jp/dp/B0074D3QCK/
  - ケーブルでなくアダプタ (テスト時用) https://www.amazon.co.jp/gp/product/B01GFOOXO8/

**Comment by dynamis** [comment]
ドキュメントの追加が必要なところ

- [ ] 全体の流れの紹介 (需要に合わせて単体利用とローカル通知・表示機能込みの場合といろいろな構成で使えることの説明)
- [ ] 画面と音によるローカル通知を利用する場合の設定方法と使い方を説明するページ
  - Kuman の 3.5 inch ディスプレイの輝度を保存する方法ってないかな？起動時デフォルト 80% なのを 100% にしたいが無理？
- [ ] 機材購入先ページ (purchase.md) への追記

**Comment by kou029w** [comment]
未検証ですけど明るさなどはドライバーをインストールすれば可能かもしれません
https://github.com/goodtft/LCD-show

**Comment by dynamis** [comment]
なるほど。そしてソフトウェアでは出来ないって issue に書いてありましたので無理で確定:
- Screen brightness https://github.com/goodtft/LCD-show/issues/127
- Siwtch off 3.5 inch Screen https://github.com/goodtft/LCD-show/issues/141
- 改造方法: https://www.raspberrypi.org/forums/viewtopic.php?t=149887

**Comment by kou029w** [comment]
https://webdino.github.io/pizero-workshop/Workshop2ndPage.html の末尾にリンクを書き加えました。
画面、読み上げ、それぞれのセットアップ方法は
https://webdino.github.io/pizero-workshop/ForDevelopers/web-agent.html
https://webdino.github.io/pizero-workshop/ForDevelopers/speech-agent.html
に記載しました

**Comment by kou029w** [comment]
機材購入一覧にリンクを加えました https://webdino.github.io/pizero-workshop/purchase.html

**Comment by kou029w** [comment]
> * 全体の流れの紹介 (需要に合わせて単体利用とローカル通知・表示機能込みの場合といろいろな構成で使えることの説明)

こちらは最低限 https://webdino.github.io/pizero-workshop/Workshop2ndPage.html に説明を加えました
