### ISSUE TITLE
SSH 接続やドライバインストールがが不要なワークショップに

### ISSUE THREAD

**Issue by dynamis** [webdino/pizero-workshop#4]
一般的な開発では ssh 接続して raspi 上でいろいろな操作をするのだが、子供だったり非エンジニアが体験できるように、ssh などのツールのインストールや usb で接続する場合はドライバーのインストールが必要だったり、多数同時にやる場合には各端末の host 名を変えて bonjour で特定するようにしたりする。

もはや sd カードを編集するだけで計測データを収集できるものにしてしまい、どちらかというとデータの分析などの方に重きをおいたワークショップにしていくべき。

- [x] すべてインストール済み、node_modules も入っている状態を用意
  - [x] できればセットアップスクリプトも用意する
- [x] 動作確認と可視化用に ambient に投げつつも同時にローカル csv にも書き出すように
  - [x] ローカル CSV がどの程度のペースで容量を食うのか、logrotate で圧縮した場合でも boot パーティーションを食い潰さないか確認しておく。必要なら sdcard 容量大きくする等も検討
- [x] 特定のファイル名で Wifi ssid/pass を書いたら wpa supplicant 生成する起動スクリプトを用意
- [ ] sd イメージ作成手順を更新
- [x] チュートリアルの手順も sd リーダーでファイル書き換えて電源入れるだけに更新
- [ ] ssh したりする手順については参考・上級者向け的に残す

**Comment by dynamis** [comment]
初心者向けには Raspbian Desktop (full ではない、こちらが優先)、企業向けには Raspbian Buster Lite で両方用意できるのが望ましい:
https://www.raspberrypi.org/downloads/raspbian/

ファイルパス (既存のものから変更 #6)
- /home/pi
  - Omron2jcieBu01 - node プログラム一式のディレクトリ
    - config.js - 設定ファイル https://github.com/webdino/pizero-workshop/blob/master/config.js
    - node_modules - npm i でインストール済みの状態に
  - wifi.config (ファイル名は仮)
    - 起動時に確認して wpa_wuppplicant の更新をする対象
- /etc/systemd/system/
  - omron2jciebu01.service - サービスとして登録

**Comment by dynamis** [comment]
note: OMRON センサーに接続するだけでなく他のセンサーに対応するとか Ambient 以外にデータを送るとかデータの送り方をカスタマイズするとか、設定内容を増やしていくことになるのであれば sdcard には github リポジトリの URL を書いてそれを clone/pull あるいは単に任意の URL を書いてそのファイルを wget して設定ファイルとして読み込むようにすれば sdcard リーダーを毎回使わずに済むようには出来る。

**Comment by dynamis** [comment]
Windows / Chromebook / Mac に全対応する必要があるようなので要注意

- [ ] sdcard の書き換えは FAT の boot パーティーション (/boot としてマウント) のみなので、参加者が書き換える必要があるものはそこに集約させる (上記フォルダパス案を修正)
- [ ] Windows メモ帳で開いて保存してファイルの頭に BOM 付けて保存されても問題ないか要確認
- [ ] ファイルの構文チェックをどうするか。js であれば CodeSandbox などに突っ込んで編集させれば良い気がする
  - ブラウザで https://codesandbox.io/s/github/webdino/pizero-workshop?module=config.js を開いて編集し、それを sdcard に書き込ませる

**Comment by dynamis** [comment]
Ambient に送ると同時にローカル記録する csv データの出力先も /boot/log/ 配下にしておきましょう。FAT 領域にガンガン書き込むのは (容赦なく電源断されることが想定されるので) 危険度が高いので直接書くのは /home/pi/log/ にして時々 /boot/log/ にコピーするくらいでしょうか。

あるいはそもそも csv ファイルを読むために一度電源を切って sdcard 抜き出すと計測が中断してしまうし面倒なので、Google Drive や Dropbox などに rclone https://rclone.org/ させる方が良いかも。

- [ ] cvs ログデータを Google Drive などに保存させることを検討

**Comment by dynamis** [comment]
/home/pi/Omron2jcieBu01 ディレクトリと想定していたが、OMRON 以外のデータも取って送る可能性も想定して何らかのプロジェクト名ディレクトリ (今のところ仮に bird ) で /home/pi/bird としましょう。

**Comment by dynamis** [comment]
sdcard に設定を書き込んだらデータ送信できることは確認したが、自動起動してすぐにデータの取得を始めてしまうと最初の送信データのタイムスタンプが狂う。

これは RasPi が RTC を持っておらず長時間電源を入れていないと時刻がずれるからだが、sdimage 書き換えて最初にネット接続したときには必ず発生することなので、ntp で時刻合わせをしてからデータの記録を開始するようにしなければならない。

- [ ] 起動直後に WiFi 接続が出来たら NTP で時刻修正を行ってから各種処理を始める

**Comment by takashinishio** [comment]
起動後最初の送信データのタイムスタンプ問題は、まずpingの確認、その後timesyncdの再起動、そしてセンシングを開始する、で対応できました。

**Comment by dynamis** [comment]
完了済みクローズ
