### ISSUE TITLE
Machinist 対応 (Ambient 以外のデータ収集・可視化サービス検討)

### ISSUE THREAD

**Issue by dynamis** [webdino/pizero-workshop#7]
Ambient は超簡単に試すのにはいいけど色々制約あるので他に手軽でもう少し柔軟なものがないか調査・検討している。

## Machinist
https://machinist.iij.jp

10 metric を 1 ヶ月分までは無料。1 ヶ月だけだと基本的には有料で使う前提で最初無料というイメージになる。Pro 向けプランは準備中だが、長期保存に対応すればお手軽に使えるデータ保存・可視化・閾値通知サービスとしては良いかもしれない。

ベータ時点の紹介資料:
https://www.iij.ad.jp/dev/tech/technight/pdf/20181214-TECHNIGHT-VOL6-Session1.pdf
Nodeのサンプルコード:
http://route-b.iij.ad.jp/archives/1309

## Azure IoT Hub
https://azure.microsoft.com/ja-jp/pricing/details/iot-hub/
https://azure.microsoft.com/ja-jp/free/free-account-faq/

0.5KB までのサイズで 8000 メッセージ/日までなら無料。但しアカウントのセットアップにはクレジットカード (またはデビットカード) が必要なので学生個人向けではない。企業向けのトレーニングにならその後の拡張性もあってとても良いがある程度のレベルが求められる。

グラフを描く機能などは別で Azure App Service なども連携させる必要がある
https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-hub-live-data-visualization-in-web-apps
https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-hub-live-data-visualization-in-power-bi

## Elasticsearch + Kibana
https://www.elastic.co/products/elasticsearch
https://www.elastic.co/jp/products/kibana

広く使われている実践的なものだが、このワークショップのようなレベルのサンプルとしては本格的すぎだし、学校や学生が使うのには 14 日間限定の無償サービスなどしかなさそうでお手軽ではない

- Amazon Elasticsearch Service https://aws.amazon.com/jp/elasticsearch-service/
  - EC2 micro の無料枠で稼働可能だが EBS ストレージボリュームの累積サイズ、スタンダード AWS データ転送料金もあるので完全無料になるのかは分からないし何にしてもカード登録が必要なのは学生向けではない。
- Elastic Cloud https://www.elastic.co/jp/downloads/
  - $17/月〜 https://www.elastic.co/jp/products/elasticsearch/service/pricing

## InfluxDB/ES/etc + Grafana
https://grafana.com/get

ES + Kibana より少しシンプル、データは ElasticSearch に限らないのでいろいろなデータを可視化するのに便利で grafana 側は hosted で無料なものもあるが DB 側の課金もあるし初学者向けには複雑すぎる

**Comment by bathtimefish** [comment]
ぼくは上記全部使ったことがあって、このセミナーには敷居が高すぎると判断してAmbientを選択しました。

上記よりはPowerBIのほうが簡単かもだけどWindows限定なのとやっぱりAmbientが簡単
https://docs.microsoft.com/ja-jp/power-bi/developer/overview-of-power-bi-rest-api

**Comment by dynamis** [comment]
コメントありがとうございます。多分そうだろうなと思いつつ、他のものがどうなのかというのをメモしておこうというつもりで取りあえず列挙・メモを追記していっている感じです。

ただ、企業で使う際に有料でも良いからしっかりデータを貯めて分析する形に発展させていこうとすればどうするのが良いのだろうというのが悩みどころです。

先月 IIJ がリリースした machinist (上記にも追記) はこのセミナーレベルでも使える＆メール通知までできて、準備中ですが Pro プランで長期間データ保存とか出来るかもと思ったりします:

https://machinist.iij.jp/
https://www.iij.ad.jp/news/pressrelease/2019/0711-2.html

**Comment by dynamis** [comment]
Machinist については IIJ IoT のサブセットとしてデータ受信・可視化・通知だけを切り出したものらしく、同じような API で IIJ IoT へのデータ送信なども可能、最初のお試し的な感じで切り出したものになっている様子

- IIJ IoT https://www.iij.ad.jp/biz/iot/
- API は違うが比較的近い感じ。ドキュメントは IIJ IoT の方が仕様が不明確で Machinist の方がしっかりいているというのが面白い状態
  - Machinist API https://machinist.iij.jp/getting-started/spec/data_format.html
  - IIJ IoT - デバイスモニタリングの API http://manual.iij.jp/iot/doc/14158765.html

AWS/GCP/Azure に移行できないレベルの人が使うのには IIJ IoT は使いやすそうで、更に簡易化されたものが Machinist だと思うとアップグレードパスまで考えられている (考えようとしている) のがとても良い印象。

Machinist で現在不明なのはデータのエクスポート機能の有無。グラフ表示している 100 件分を csv ダウンロードは出来るが保持している 6 ヶ月分のデータをまるごとエクスポートする機能が見当たらないので確認中。まぁ csv フルデータが欲しい場合はローカルにも csv 保存しておくのを使うことは出来るだろうし Ambient でも古いデータを全部 DL することはできないので致命的な問題ではないと思うと Ambient から Machinist に移行した方がよさそう。

**Comment by dynamis** [comment]
改善したいところは色々あるけど取りあえず Machinist に送信＆ CSV 保存も可能となっているのでクローズ

https://github.com/webdino/pizero-workshop/commit/b740393c1514d73ac4768525fc07d152dc1c9842
