### ISSUE TITLE
月間通信量の概算

### ISSUE THREAD

**Issue by dynamis** [webdino/pizero-workshop#9]
このワークショップのセットアップで利用した場合にどの程度の通信量になるか概算をしておきたい

- OMRON 環境センサーデータのアップロードにかかる通信
  - [ ] Machinist 利用時
  - [ ] Ambient 利用時
  - [ ] Machinist + Ambient 利用時

WiFi ではなく IoT 向けの小容量 SIM を使ったデータ通信環境で利用する場合の参考あるいは、データ送信頻度の上限を事前に把握できるようにするため。

**Comment by dynamis** [comment]
例えば Machinist に次のデータを送信した場合:

- request: body 917 + header 315 = 1.24KB
- response: body 23 + header 705 = 0.7KB

これに IP/HTTP ヘッダが付与されるのが通信量、変動するしざっくり 2KB くらい。Machinist は 1 分に 1 度が記録される上限なので

  2KB * (24*60*31) = 89280 KB 程度/月

で月 100MB くらいの帯域を確保していれば毎分データ送信が可能。
通信容量が少ない SIM 等を使う場合には頻度を落とすか前回からの変動が少ないときは送信を省略するか、何か工夫をすれば良い感じ。

```
{"agent":"playground","metrics":[
{
  "name": "温度",
  "namespace": "2JCIE-BU",
  "data_point": {
    "timestamp": 1565946722,
    "value": 27.6
  }
},
{
  "name": "湿度",
  "namespace": "2JCIE-BU",
  "data_point": {
    "timestamp": 1565946722,
    "value": 40.2
  }
},
{
  "name": "大気圧",
  "namespace": "2JCIE-BU",
  "data_point": {
    "timestamp": 1565946722,
    "value": 998
  }
},
{
  "name": "騒音",
  "namespace": "2JCIE-BU",
  "data_point": {
    "timestamp": 1565946722,
    "value": 72
  }
},
{
  "name": "照度",
  "namespace": "2JCIE-BU",
  "data_point": {
    "timestamp": 1565946722,
    "value": 1200
  }
},
{
  "name": "総揮発性有機化合物濃度",
  "namespace": "2JCIE-BU",
  "data_point": {
    "timestamp": 1565946722,
    "value": 130
  }
},
{
  "name": "二酸化炭素",
  "namespace": "2JCIE-BU",
  "data_point": {
    "timestamp": 1565946722,
    "value": 1520
  }
}
]}
```

**Comment by dynamis** [comment]
```
tcpdump host 202.221.51.40 -s0 -w test.dump
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${api_key}" https://gw.machinist.iij.jp/endpoint -d @- < machinist.json
```

とかすると総計 22 パケット送受信され合計 22 パケット 7064 Bytes 送受信していた。

![image](https://user-images.githubusercontent.com/188166/63168215-86ae0d80-c06e-11e9-8139-00ec8ee06d08.png)

思っていたより重い。curl じゃなくて node で false start できればマシかな？サーバも TLS1.3 に対応して Node 12 を使えば PSK (事前共有鍵) で再接続するなどして軽量化できるんだろうけど。

**Comment by takashinishio** [comment]
![Screenshot from 2019-09-01 13-28-19](https://user-images.githubusercontent.com/49295280/64089084-5f01b980-cd7f-11e9-87ea-65fe99700c63.png)
センシング１回（つまり毎分）でMachnistに送信した場合と、センシング１０回毎にまとめて（つまり１０分に一度）送信した場合の通信量比較グラフ。
カラムは、時刻 , RX(bytes) , RXerror , TX(bytes) 。
cronで毎分ifconfigして、その結果をcsv形式で追記。
15:33に「毎分計測と毎分送信」の設定で起動、15:44に「毎分計測１０分毎に送信」の設定で起動させたもの。
これを見る限り、10回分まとめて送信すると大体通信量1/3ぐらいに抑えられる。
この場合、10分に一回送信で10KB程度、概算上は1.4MB/day、43.2MB/month程度の通信量になる。

**Comment by dynamis** [comment]
43.2MB/month ならかなりマシですね。

毎回送信だとすると月 120 を越えるとしても curl との差が 2 倍以上あるのは node で連続通信していると無駄なハンドシェイクが少なくなるからだと思うが詳細は未確認 (要 tcpdump)

取りあえず概算は出来て通信量もそれなりに抑えられることが分かったのでクローズ。
